jobs:
  - ${{ each mongoDriverVersion in parameters.mongoDriverVersions }}:
      - job:
        displayName: ${{ format('MongoDB Driver Version:{0}', mongoDriverVersion) }}
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: Install .Net Core 3.1.x SDK
            inputs:
              packageType: sdk
              version: '3.1.x'

          - script: sed -i -E "s/(<PackageReference Include=\"MongoDB.Driver\" Version=\").*(\" \/>)/\1${{ mongoDriverVersion }}\2/" ./tests/Elastic.Apm.Mongo.IntegrationTests/Elastic.Apm.Mongo.IntegrationTests.csproj
            displayName: Replace MongoDB.Driver version

          - script: cat ./tests/Elastic.Apm.Mongo.IntegrationTests/Elastic.Apm.Mongo.IntegrationTests.csproj
            displayName: Print replaced content

          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              # disable parallel restore due to https://github.com/GitTools/GitVersion/issues/1381
              arguments: '--disable-parallel --configuration $(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              arguments: '--no-restore --configuration $(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test
              arguments: '--no-build --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
