jobs:
  - ${{ each mongoDriverVersion in parameters.mongoDriverVersions }}:
      - job:
        displayName: ${{ format('MongoDB Driver Version:{0}', mongoDriverVersion) }}
        variables:
          # workaround due to https://github.com/GitTools/GitVersion/pull/2221
          MSBUILDSINGLELOADCONTEXT: 1
        pool:
          vmImage: windows-2019
      steps:
        - task: UseDotNet@2
          displayName: Install .Net Core 2.2.x SDK
          inputs:
            packageType: sdk
            version: '2.2.x'

        - task: UseDotNet@2
          displayName: Install .Net Core 3.1.x SDK
          inputs:
            packageType: sdk
            version: '3.1.103'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: build
            arguments: '--configuration $(buildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
            nobuild: true
            